### ISSUE TITLE
Login te lleva a la sección de ver mis encuentros.

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/votainteligente-portal-electoral#848]

**Comment by alexmartz001** [comment]
Hola he instalado segun lo indicado pero me presenta el siguiente error, talvez alguna recomendacion

ubuntu@ip-172-26-8-246:~/votainteligente-portal-electoral$ sudo python manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x7f35934ff1b8>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    autoreload.raise_last_exception()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named test_without_migrations
^Cubuntu@ip-172-26-8-246:~/votainteligente-portal-electoral$
